allowBuilds:
  '@swc/core': true
  core-js: true
  core-js-pure: true

blockExoticSubdeps: false

ignoredBuiltDependencies:
  - '@swc/core'

minimumReleaseAge: 1440

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - detect-port@1.6.1
  - semver@6.3.1
